mysql:
  url: ${DATABASE_MSQL_URL:localhost:3306}
  username: ${DATABASE_MYSQL_USERNAME:localhostroot}
  password: ${DATABASE_MYSQL_PASSWORD:Crip@@4071}
  schema: adm_videos

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none